namespace UsedCarHub.Domain.Enums
{
    public enum Marks
    {
        Toyota = 1,
        Volkswagen = 2,
        Ford = 3,
        Nissan = 4,
        Honda = 5,
        Hyundai = 6,
        Chevrolet = 7,
        Kia = 8,
        Mercedes = 9,
        Renault = 10,
        BMW = 11,
        Peugeot = 12,
        Audi = 13,
        Maruti = 14,
        Mazda = 15,
        Jeep = 16,
        Suzuki = 17,
        Fiat = 18,
        Geely = 19,
        Buick = 20,
        Skoda = 21,
        Mitsubishi = 22,
        Changan = 23,
        Wuling = 24,
        Subaru = 25,
        Citroen = 26,
        Opel = 27,
        Baojun = 28,
        Daihatsu = 29,
        Dongfeng = 30,
        Haval = 31,
        Ram = 32,
        Lexus = 33,
        Dacia = 34,
        GMC = 35,
        Volvo = 36,
        Chery = 37,
        Dodge = 38,
        Trumpchi = 39,
        Seat = 40,
        BYD = 41,
        Roewe = 42,
        Baic = 43,
        LandRover = 44,
        Saipa = 45,
        JAC = 46,
        Cadillac = 47,
        Lada = 48,
        Isuzu = 49,
        Mini = 50
    }
}